// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanK5FB6Nn4K4seUoqX89jo281yBN__hQ',
    appId: '1:308964077188:web:2f0984a72786c05028dcd1',
    messagingSenderId: '308964077188',
    projectId: 'santhosh-62603',
    authDomain: 'santhosh-62603.firebaseapp.com',
    storageBucket: 'santhosh-62603.firebasestorage.app',
    measurementId: 'G-WLLCE1QTN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgMIme1xzh87bWO3cZ4Al95HzZcnuerc',
    appId: '1:308964077188:android:85a3557db2b5a86928dcd1',
    messagingSenderId: '308964077188',
    projectId: 'santhosh-62603',
    storageBucket: 'santhosh-62603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD62lm-A_9OPC2WJkcvB9Y02YkOHqOznM8',
    appId: '1:308964077188:ios:01236e921cbbbf6e28dcd1',
    messagingSenderId: '308964077188',
    projectId: 'santhosh-62603',
    storageBucket: 'santhosh-62603.firebasestorage.app',
    iosBundleId: 'com.example.santhosh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD62lm-A_9OPC2WJkcvB9Y02YkOHqOznM8',
    appId: '1:308964077188:ios:01236e921cbbbf6e28dcd1',
    messagingSenderId: '308964077188',
    projectId: 'santhosh-62603',
    storageBucket: 'santhosh-62603.firebasestorage.app',
    iosBundleId: 'com.example.santhosh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanK5FB6Nn4K4seUoqX89jo281yBN__hQ',
    appId: '1:308964077188:web:9f65308acd223cc628dcd1',
    messagingSenderId: '308964077188',
    projectId: 'santhosh-62603',
    authDomain: 'santhosh-62603.firebaseapp.com',
    storageBucket: 'santhosh-62603.firebasestorage.app',
    measurementId: 'G-RQY82YB2L8',
  );

}